#ifndef __NMEA__AAM__HPP__
#define __NMEA__AAM__HPP__

#include <marnav/nmea/sentence.hpp>
#include <marnav/utils/optional.hpp>

namespace marnav
{
namespace nmea
{

/// @brief AAM - Waypoint Arrival Alarm
///
/// This sentence is generated by some units to indicate the status of arrival (entering
/// the arrival circle, or passing the perpendicular of the course line) at the destination
/// waypoint.
///
/// @code
///        1 2 3   4 5
///        | | |   | |
/// $--AAM,A,A,x.x,N,c--c*hh<CR><LF>
/// @endcode
///
/// Field Number:
/// 1. Status
///    - A = arrival circle entered
///    - V = arrival circle not entered
/// 2. Status
///    - A = perpendicular passed at waypoint
///    - V = perpendicular not passed
/// 3. Arrival circle radius
/// 4. Units of radius
///    - N = nautical miles
/// 5. Waypoint ID
///
/// Example: <tt>$GPAAM,A,A,0.10,N,WPTNME*43</tt>
///
/// WPTNME is the waypoint name.
///
class aam : public sentence
{
public:
	constexpr static const sentence_id ID = sentence_id::AAM;
	constexpr static const char * TAG = "AAM";

	aam();
	aam(const aam &) = default;
	aam & operator=(const aam &) = default;

	static std::unique_ptr<sentence> parse(const std::string & talker,
		const std::vector<std::string> & fields) throw(std::invalid_argument,
		std::runtime_error);

protected:
	virtual std::vector<std::string> get_data() const override;

private:
	utils::optional<status> arrival_circle_entered;
	utils::optional<status> perpendicualar_passed;
	utils::optional<double> arrival_circle_radius;
	utils::optional<unit::distance> arrival_circle_radius_unit;
	utils::optional<std::string> waypoint_id;

	void check() const throw(std::invalid_argument);

public:
	NMEA_GETTER(arrival_circle_entered)
	NMEA_GETTER(perpendicualar_passed)
	NMEA_GETTER(arrival_circle_radius)
	NMEA_GETTER(arrival_circle_radius_unit)
	NMEA_GETTER(waypoint_id)

	void set_arrival_circle_entered(status s);
	void set_perpendicular_passed(status s);
	void set_arrival_circle_radius(double t);
	void set_waypoint_id(const std::string & id);
};
}
}

#endif
